## Write a Numpy program to compute the multiplication of two given matrixes

In [2]:
import numpy as np
def Matrix_Mult(mat1,mat2):
    product = np.dot(mat1,mat2)
    return product

In [3]:
mat1 = np.array([[1,2],
                 [3,4]
                ])
mat2 = np.array([[1,2],
                 [3,4]
                ])
Matrix_Mult(mat1,mat2)

array([[ 7, 10],
       [15, 22]])

## Write a NumPy program to compute the determinant of a given square array

In [4]:
def array_det(array):
    det = np.linalg.det(array)
    return det

In [5]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]
             ])
array_det(A)

-9.51619735392994e-16

## Write a NumPy program to compute the cross product of two given vectors

In [9]:
def Matrix_CP(vec1,vec2):
    C_product = np.cross(vec1,vec2)
    return C_product

In [12]:
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])

Matrix_CP(vec1,vec2)

array([-3,  6, -3])

## Write a NumPy program to compute the condition number of a given matrix

In [14]:
def Con_Num(mat):
    return np.linalg.cond(mat)

In [15]:
mat = np.array([[1, 0, -1],
                [0, 1, 0],
                [1, 0, 1]
               ])
Con_Num(mat)

1.4142135623730951

## Write a NumPy program to compute the inverse of a given matrix

In [19]:
def Mat_Inv(mat):
    return np.linalg.inv(mat)

In [25]:
A = np.array([[1,2],
              [3,4]
             ])
Mat_Inv(A)
# A.dot(Mat_Inv(A))

array([[-2. ,  1. ],
       [ 1.5, -0.5]])